### ISSUE TITLE
get_random_positions returns the same results

### ISSUE THREAD

**Issue by yhwu** [BushmanLab/intSiteRetriever#11]
is this expected?

```
> get_random_positions(3, reference, 'm')
  siteID   chr strand  position
1      3 chr12      - 115298367
2      3 chr11      +  97835402
3      3  chr4      -  25417571
> get_random_positions(3, reference, 'm')
  siteID   chr strand  position
1      3 chr12      - 115298367
2      3 chr11      +  97835402
3      3  chr4      -  25417571
> get_random_positions(3, reference, 'm')
  siteID   chr strand  position
1      3 chr12      - 115298367
2      3 chr11      +  97835402
3      3  chr4      -  25417571
```

**Comment by esherm** [comment]
Yes, this is the expected behavior. The first argument here is the `siteID` which you have set to 3. The `siteID` is typically the `siteID` as recorded in the database. 

We want the same exact MRCs for each unique site (ex. site #1 has the same MRCs each and every time, but they are different MRCs than returned for site #2). This is the way that the old pipeline worked and it was a special request by Chuck. 

Since the `siteID` is always set to `3` the same MRCs are returned. If you want to change the number of MRCs, adjust the `number_of_positions` argument which is currently set to default to `3`
